### ISSUE TITLE
[Bug] Folded lists look strange...

### ISSUE THREAD

**Issue by Mistmage** [devonthesofa/obsidian-note-status#13]
Okay, that is very bizarre. But i have tested it in an empty vault and it is true.

Normally, Outliners collapsed bullet lists look like that:
![Image](https://github.com/user-attachments/assets/c1f1c2b0-8f0c-4c38-9c4b-840dbf416676)

But if Note Status is simply installed, they become like that:

![Image](https://github.com/user-attachments/assets/f40211be-23c6-46b7-be70-a9b8c2d0f755)

even more if you click around, they will move around

![Image](https://github.com/user-attachments/assets/6ed7930f-3521-4816-9507-d790d4f7cc42)

Similar effect is on the folded headings too

![Image](https://github.com/user-attachments/assets/d86e0cea-2d2a-40b4-8862-132bd0be9185)

Originally i though it was a conflict with the Outliner but last screenshot is with note status only.
So it is just an internal bug.

**Comment by soler1212** [comment]
@Mistmage I understand the issue you're describing. 

This is definitely a CSS conflict within the Note Status plugin. Looking at the styles.css file, there are a few likely culprits:
```css
/* Collapse indicators */
.collapse-indicator {
  margin-right: var(--size-4-2, 8px);
  display: flex;
  align-items: center;
  color: var(--text-muted);
  transition: transform var(--status-transition-time) var(--ease-in-out);
  opacity: 1;
}

.is-collapsed .collapse-indicator {
  transform: rotate(-90deg);
}
```

The problem is that these selectors are too generic and are affecting all `.collapse-indicator` elements in Obsidian - not just those in the Note Status plugin. This is causing the visual bugs you're seeing with collapsed bullet points and headings.

Thank you for reporting this issue! I appreciate you taking the time to test this in an empty vault and providing clear details about the problem.

I'll have this fixed for the next release.
